config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  resources :friends
  devise_for :users
  devise_scope :user do #bullshit that makes devise work
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  root "welcome#index"
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'friends#show'
  get 'search_friend', to: 'friends#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
                                  secret_token: Rails.application.credentials.iex_client[:secret_api_key],
                                  endpoint: "https://sandbox.iexapis.com/v1")

    begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  validates :first_name, presence: true
  validates :last_name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && stock_already_tracked?(ticker_symbol)
  end

  def full_name
    "#{current_user.first_name} #{current_user.last_name}"
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches("first_name", param)
  end

  def self.last_name_matches(param)
    matches("last_name", param)
  end

  def self.email_matches(param)
    matches("email", param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def friends_with?(id)
    self.friends.where(id: id).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  
  def show
    @friends = current_user.friends
  end

  def search
    if params[:friend].present?
      @friends_search = User.search(params[:friend])
      @friends_search = current_user.except_current_user(@friends_search)
      if @friends_search
        respond_to do |format|
          format.js { render partial: 'friends/result' }
        end
      else 
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid email"
          format.js { render partial: 'friends/result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter an email to search"
        format.js { render partial: 'friends/result' }
      end
    end
  end

  def destroy
    friend = current_user.friendships.where(friend_id: params[:id]).first
    friend.destroy
    flash[:notice]="Unfollowed successfully."
  end

  def create
    friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: friend.id)
    if current_user.save
      flash[:notice] = "User followed."
    else
      flash[:alert] = "Something went wrong."
    end
    redirect_to my_friends_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController 
    def home
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
    publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
    secret_token: Rails.application.credentials.iex_client[:secret_api_key],
    endpoint: "https://sandbox.iexapis.com/v1",)

    @stock = Stock.new

    @stock.ticker = ticker_symbol
    
    @stock.last_price = client.quote(ticker_symbol).latest_price
 
    @stock.name = client.company(ticker_symbol).company_name

    @stock.logo = client.logo(ticker_symbol).url
 
    @stock
  end

  def search
    if params[:stock].present?
      @stock_display = StocksController.new_lookup(params[:stock])
      if @stock_display
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
      else 
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid symbol to search"
          format.js { render partial: 'users/result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a symbol to search"
        format.js { render partial: 'users/result' }
      end
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])

    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio."
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker} was successfully removeed :D"
    redirect_to my_portfolio_path 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_result.html.erb
<% if @friends_search %>
  <div class="row">
    <% @friends_search.each do |friend| %>
      <div class="card text-dark rounded-0 alert alert-dismissable fade show col-sm-3 me-3">
        <button type="button" class="btn-close " data-bs-dismiss="alert" aria-label="Close"></button>
        <div class="card-body">
          <h5 class="card-title"><%= "#{friend.first_name} #{friend.last_name}" %></h5>
          <div class="">

            <%= link_to 'View profile', '#', class: "btn btn-sm bg-purple text-white" %>

            <% if !current_user.friends_with?(friend.id) %>
            <%= link_to 'Follow', friends_path(friend: friend), method: :create, class: "btn btn-sm bg-purple text-white" %>
            <% else %>
            <%= link_to 'Unfollow', friend_path(id: friend.id), method: :delete, class: "btn btn-sm bg-purple text-white", data: {confirm: "Are you sure?"} %>
            <% end %>

          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/friends/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'friends/result.html' %>'

app/views/friends/show.html.erb
<%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row mb-4 d-flex justify-content-center">
      <div class="no-padding-right col-sm-7">
        <%= text_field_tag :friend, params[:friend], placeholder: "--> Enter user <--", autofocus: true, class: "form-control form-control-md rounded-0" %>
      </div>
      <div class="col-sm-3 no-padding-left">
        <%= button_tag type: :submit, class: "btn bg-purple text-white rounded-0" do %>
        Search
        <% end %>
      </div>
    </div>
<% end %>

<div id="results">
  <%= render 'friends/result' %>
</div>


<% if current_user.friends.any? %>

<h3 class="text-center text-white mb-4">Your friends:</h3>

<div class = "container col-6">
  <ul class="list-group rounded-0">
    <% @friends.each do |friend| %>
      <li class="list-group-item" id="friend-display"><%= "#{friend.first_name} #{friend.last_name}" %>
      <div class = "d-flex justify-content-end">
      <%= link_to 'Remove', '#', class: "btn btn-sm bg-purple text-white" %>
      </li>
    <% end %>
  </ul>
</div>

<% else %>

<h3>You got no friends :(</h3>

<% end %>

app/views/layouts/_flash.html.erb
<% if alert %>
  <div class="container">
    <p class="notice">
    <div class="alert alert-danger alert-dismissible fade show mx-auto" role="alert">
      <%= alert %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    </p>
  </div>
<% end %>


<% if notice %>
  <div class="container">
    <p class="notice">
    <div class="alert alert-success alert-dismissible fade show mx-auto" role="alert">
      <%= notice %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    </p>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<div class="container mt-2 mb-4">
  <nav class="navbar mx-auto navbar-expand-lg rounded-0">
    <div class="container-fluid">
      <svg xmlns="http://www.w3.org/2000/svg" width="34" height="34" fill="#6f42c1" class="bi bi-suit-club-fill" viewBox="0 0 16 16">
        <path d="M11.5 12.5a3.493 3.493 0 0 1-2.684-1.254 19.92 19.92 0 0 0 1.582 2.907c.231.35-.02.847-.438.847H6.04c-.419 0-.67-.497-.438-.847a19.919 19.919 0 0 0 1.582-2.907 3.5 3.5 0 1 1-2.538-5.743 3.5 3.5 0 1 1 6.708 0A3.5 3.5 0 1 1 11.5 12.5z" />
      </svg>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse d-flex justify-content-center" id="navbarSupportedContent">
        <div>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 pe-4">
            <li class="nav-item">
              <li><%= link_to 'My portfolio', my_portfolio_path, class: "nav-link text-purple" %></li>
            </li>
            <li class="nav-item">
              <li><%= link_to 'My friends', my_friends_path, class: "nav-link text-purple" %></li>
            </li>
            <li class="nav-item">
              <%= link_to 'Profile', edit_user_registration_path, class: "nav-link text-purple" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-purple" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Session
              </a>

              <ul class="dropdown-menu rounded-0" aria-labelledby="navbarDropdown">

              <% if !user_signed_in? %>
                <li><%= link_to 'Sign in', new_user_session_path, class: "dropdown-item text-purple" %></li>
              <% end %>

              <% if user_signed_in? %>
                <li><%= link_to 'Sign out', destroy_user_session_path, class: "dropdown-item text-purple" %></li>
              <% end %>

              <% if !user_signed_in? %>
                <li><hr class="dropdown-divider"></li>
              <% end %>

              <% if !user_signed_in? %>
                <li><%= link_to 'Sign up', new_user_registration_path, class: "dropdown-item text-purple" %></li>
              <% end %>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "custom" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
</head>

<body>
    <%= render 'layouts/nav' %>

    <% if !user_signed_in? %>
        <%= render 'layouts/flash' %>

        <div class="card mx-auto rounded-0 mt-5" id="login-card" style="width: 30%;">
            <div class="card-body">                
                <%= yield %>
            </div>
        </div>

    <% else %>
        <%= render 'layouts/flash' %>

        <div class="mx-auto" style="width: 80%;">            
            <%= yield %>
        </div>

    <% end %>
</body>

</html>

app/views/stocks/search.html.erb
<h3 class="text-white"><%= "#{@stock_display.ticker}, #{ @stock_display.name}, #{ @stock_display.last_price}" %></h3>

app/views/users/_result.html.erb
<% if @stock_display %>
<div class="card text-dark rounded-0 alert alert-dismissable fade show" style="width: 18rem;">
  <button type="button" class="btn-close " data-bs-dismiss="alert" aria-label="Close"></button>
  <div class="card-body">
    <h5 class="card-title"><%= @stock_display.name %></h5>
    <p class="card-text"><strong>Most recent price: </strong><%= @stock_display.last_price %></p>

    <% if current_user.can_track_stock?(@stock_display.ticker) %>
    <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock_display.ticker), class: "btn bg-purple rounded-0 text-white", method: :post %>
    <% else %>
    <span class="badge bg-primary">
      You are already tracking
      <% if !current_user.under_stock_limit? %>
      10 socks
      <% end %>
      <% if current_user.stock_already_tracked?(@stock_display.ticker) %>
      this sock
      <% end %>
    </span>
    <% end %>



  </div>
</div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/result.html' %>'

app/views/users/my_portfolio.html.erb
<div class="row">
  <div class="text-white colt-5">
    <div class="mb-3">
      <h2>Search stocks</h2>
    </div>

    <div class="mt-2">
      <p>Hi <%= current_user.first_name %>, this is your portfolio page. </p>
    </div>

    <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-4 no-padding-right">
        <%= text_field_tag :stock, params[:stock], placeholder: "--> Enter Stock ticker <--", autofocus: true, class: "form-control form-control-md rounded-0" %>
      </div>
      <div class="col-sm-3 no-padding-left">
        <%= button_tag type: :submit, class: "btn bg-purple text-white rounded-0" do %>
        Search
        <% end %>
      </div>
    </div>
    <% end %>

    <div class="mt-3">
      <div id="results">
        <%= render 'users/result' %>
      </div>
    </div>
  </div>

  <div class="col-5">
    <%= image_tag "portfolio.png", id: "home-image", class: "d-inline" %>
  </div>
</div>

<% if !@tracked_stocks.empty? %>
<div class="row col-9">
  <table class="table text-white">
    <thead>
      <tr>
        <th scope="col">Ticker</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @tracked_stocks.each do |stock| %>
      <tr>
        <th scope="row"><%= stock.ticker %></th>
        <td><%= stock.name %></td>
        <td><%= stock.last_price %></td>
        <td>
          <%= link_to 'Unfollow', user_stock_path(stock), method: :delete, class: "btn bg-purple text-white rounded-0", data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
      <% end %>

    </tbody>
  </table>
</div>
<% end %>

app/views/welcome/index.html.erb
<h1 class="text-center text-white mt-3">Welcome to the index page</h1>